import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col h-screen justify-center gap-y-[1vh] md:px-10 px-5'>
        <h1 >
          <span className={styles.title}>
          Shalom, <br />
          I'm Naaman
          </span>
          <span className='text-sm md:text-xl raleway '>
            (my friends call me Nemo)
          </span>
        </h1>

        <h2 className={styles.title}>
        Front-End Architect
        </h2>
      </main>
    </div>
  )
}
